# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cortex' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cortex
  #pod 'FileKit'
  #pod 'AEXML-CU'
  pod 'ReactiveCocoa', '~> 6.0'
end
